# Konfiguracja dla fine-tuningu modeli

# Podstawowe ustawienia
model:
  name: "microsoft/DialoGPT-small"  # Mały model do testów
  path: ""                          # Pusty path dla modeli HuggingFace
  max_length: 256          # Maksymalna długość sekwencji
  padding: "right"         # Kierunek paddingu

# Ustawienia treningu
training:
  output_dir: "./output"
  num_train_epochs: 1
  per_device_train_batch_size: 2
  per_device_eval_batch_size: 2
  gradient_accumulation_steps: 4
  learning_rate: 5.0e-5
  weight_decay: 0.01
  warmup_steps: 5
  logging_steps: 2
  save_steps: 10
  eval_steps: 10
  evaluation_strategy: "steps"
  save_strategy: "steps"
  load_best_model_at_end: true
  metric_for_best_model: "eval_loss"
  greater_is_better: false
  
# Ustawienia LoRA
lora:
  enabled: true
  r: 16
  lora_alpha: 32
  lora_dropout: 0.1
  target_modules:
    - "c_attn"
    - "c_proj"
    - "c_fc"

# Ustawienia optymalizacji pamięci
memory_optimization:
  gradient_checkpointing: false
  dataloader_pin_memory: false
  fp16: false
  bf16: false
  use_8bit_optimizer: false

# Ustawienia danych
data:
  train_file: "./data/train_train.jsonl"
  eval_file: "./data/train_val.jsonl"
  max_train_samples: null  # null = użyj wszystkich
  max_eval_samples: null
  
# Ustawienia logowania
logging:
  use_wandb: false
  wandb_project: "fine-tuning"
  use_tensorboard: true
  log_level: "INFO"

# Ustawienia seed
seed: 42
